server:
  port: 8015
  servlet:
    contextPath: /task
spring:
  application:
    name: task
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/task}
      auto-index-creation: true